#PORTA SERVIDOR LOCAL
server:
  port: 8080
#INFORMAÇÕES DE MONITORAÇÃO
info:
  app:
    name: OAuthApplication
    description: API de controle de acesso de usuario do sistema
    documentation: http://localhost:8080/swagger-ui.html
#CONFIGURAÇÃO DE ACESSO AO BANCO DE DADOS
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hmtf_db?useSSl=false
    username: admin
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show_sql: true
    format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
    hibernate:
      ddl-auto: validate
#CONFIGURAÇÕES DE LOG
logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: INFO
#CONFIGURAÇÕES DE JWT
jwt:
  secret: and0YXBwc2VjdXJpdHlwaHJhc2U=
  expiration: 1800